name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    if: (!contains(github.event.head_commit.message, '[skip ci]')) && (!contains(github.event.head_commit.message, '[ci skip]'))

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.5.7
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: rake test
